cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/cask-fonts'

brew 'bat'
brew 'broot'
brew 'bottom' # 'btm' is the cli binary
brew 'csvkit'
brew 'fd'
brew 'fx'
brew 'gh'
brew 'git'
brew 'git delta'
brew 'jq'
brew 'keith/formulae/reminders-cli'
brew 'lazydocker'
brew 'lsd'
brew 'm-cli'
brew 'mas'
brew 'navi'
brew 'neofetch'
brew 'nickgerace/gfold/gfold'
brew 'onefetch'
brew 'ripgrep'
brew 'sk'
brew 'so'
brew 'starship'
brew 'svn' #omg I need this to get the fonts
brew 'wget'
brew 'yt-dlp'
brew 'zoxide'

cask '1password'
cask 'appcleaner'
cask 'discord'
cask 'docker'
cask 'firefox'
cask 'font-fira-code-nerd-font'
cask 'font-source-code-pro'
cask 'font-source-sans-pro'
cask 'google-chrome'
cask 'kap'
cask 'raycast'
cask 'rectangle'
cask 'rocket'
cask 'sketch'
cask 'skitch'
cask 'slack'
cask 'transmit'
cask 'visual-studio-code'
cask 'xscope'