#!/usr/bin/env zsh
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# Run Homebrew through the Brewfile
echo "› brew bundle"
brew bundle
# find the installers and run them iteratively
find . -name install.zsh | while read installer ; do sh -c "${installer}" ; done
